{% set version = "3.20.1" %}

package:
  name: libdap4
  version: {{ version }}

source:
  url: https://github.com/OPENDAP/libdap4/archive/version-{{ version }}.tar.gz
  sha256: 455dc01ea344c7711cb8dd7ec983e72ff764073bab9ce93ef9b60aafc8c27b27

build:
  number: 1000
  skip: True  # [win or (cxx_compiler == 'toolchain_cxx')]
  run_exports:
    # no ABI lab entry.  Going with minor pinning based on past conda-forge pinning.
    - {{ pin_subpackage('libdap4', max_pin='x.x') }}

requirements:
  build:
    - automake
    - autoconf
    - libtool
    - flex
    - bison 3.0.4
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libxml2
    - curl
    - libuuid  # [not osx]
    - flex
  run:
    - libxml2
    - curl
    - libuuid  # [not osx]

test:
  commands:
    - dap-config --version

about:
  home: http://www.opendap.org
  license: GNU LGPL
  license_file: COPYING
  summary: 'A C++ SDK which contains an implementation of both DAP2 and DAP4'

extra:
  recipe-maintainers:
    - aleksandervines
    - jakirkham
    - ocefpaf
    - msarahan
