{% set version = "3.20.0" %}

package:
  name: libdap4
  version: {{ version }}

source:
  url: https://github.com/OPENDAP/libdap4/archive/version-{{ version }}.tar.gz
  sha256: 8f73ea257335729afb25e85a344b8a6f4e8cf62bccbb3282532f8e779bcd84e5

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - automake
    - autoconf
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - flex
    - bison 3.0.4
    - libxml2
    - curl
    - libuuid  # [not osx]
  run:
    - libxml2
    - curl
    - libuuid  # [not osx]

test:
  commands:
    - dap-config --version

about:
  home: http://www.opendap.org
  license: GNU LGPL
  license_file: COPYING
  summary: 'A C++ SDK which contains an implementation of both DAP2 and DAP4'

extra:
  recipe-maintainers:
    - aleksandervines
    - jakirkham
    - ocefpaf
