{% set version = "3.19.1" %}

package:
  name: libdap4
  version: {{ version }}

source:
  url: https://github.com/OPENDAP/libdap4/archive/version-{{ version }}.tar.gz
  sha256: 487c86ad95b45a83e9f0fc09b69107f6b035d7373c2a7a717532b6e31b1cb6ee

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - automake
    - autoconf
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - flex
    - bison 3.0.4
    - libxml2
    - curl
    - libuuid  # [not osx]
  run:
    - libxml2
    - curl
    - libuuid  # [not osx]

test:
  commands:
    - dap-config --version

about:
  home: http://www.opendap.org
  license: GNU LGPL
  license_file: COPYING
  summary: 'A C++ SDK which contains an implementation of both DAP2 and DAP4'

extra:
  recipe-maintainers:
    - aleksandervines
    - jakirkham
    - ocefpaf
